// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ClusterStatusApplyConfiguration represents an declarative configuration of the ClusterStatus type for use
// with apply.
type ClusterStatusApplyConfiguration struct {
	KubeConfigURL *string `json:"kubeconfigUrl,omitempty"`
	Context       *string `json:"context,omitempty"`
}

// ClusterStatusApplyConfiguration constructs an declarative configuration of the ClusterStatus type for use with
// apply.
func ClusterStatus() *ClusterStatusApplyConfiguration {
	return &ClusterStatusApplyConfiguration{}
}

// WithKubeConfigURL sets the KubeConfigURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubeConfigURL field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithKubeConfigURL(value string) *ClusterStatusApplyConfiguration {
	b.KubeConfigURL = &value
	return b
}

// WithContext sets the Context field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Context field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithContext(value string) *ClusterStatusApplyConfiguration {
	b.Context = &value
	return b
}
