// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SeedSpecApplyConfiguration represents an declarative configuration of the SeedSpec type for use
// with apply.
type SeedSpecApplyConfiguration struct {
	SeedURL *string `json:"seedUrl,omitempty"`
	Planted *bool   `json:"planted,omitempty"`
}

// SeedSpecApplyConfiguration constructs an declarative configuration of the SeedSpec type for use with
// apply.
func SeedSpec() *SeedSpecApplyConfiguration {
	return &SeedSpecApplyConfiguration{}
}

// WithSeedURL sets the SeedURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SeedURL field is set to the value of the last call.
func (b *SeedSpecApplyConfiguration) WithSeedURL(value string) *SeedSpecApplyConfiguration {
	b.SeedURL = &value
	return b
}

// WithPlanted sets the Planted field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Planted field is set to the value of the last call.
func (b *SeedSpecApplyConfiguration) WithPlanted(value bool) *SeedSpecApplyConfiguration {
	b.Planted = &value
	return b
}
