// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SeedStatusApplyConfiguration represents an declarative configuration of the SeedStatus type for use
// with apply.
type SeedStatusApplyConfiguration struct {
	PlantedPath *string `json:"plantedPath,omitempty"`
}

// SeedStatusApplyConfiguration constructs an declarative configuration of the SeedStatus type for use with
// apply.
func SeedStatus() *SeedStatusApplyConfiguration {
	return &SeedStatusApplyConfiguration{}
}

// WithPlantedPath sets the PlantedPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PlantedPath field is set to the value of the last call.
func (b *SeedStatusApplyConfiguration) WithPlantedPath(value string) *SeedStatusApplyConfiguration {
	b.PlantedPath = &value
	return b
}
