// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// ClusterNamespaceListerExpansion allows custom methods to be added to
// ClusterNamespaceLister.
type ClusterNamespaceListerExpansion interface{}

// SeedListerExpansion allows custom methods to be added to
// SeedLister.
type SeedListerExpansion interface{}

// SeedNamespaceListerExpansion allows custom methods to be added to
// SeedNamespaceLister.
type SeedNamespaceListerExpansion interface{}
